cp/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.contrib.auth import views as v
from users.views import user_login
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
	path('',views.home,name='home'),
    path('accounts/login/', user_login, name='login'),
    path('login/', user_login, name='login'),
    path('accounts/logout/', v.logout_then_login, name='logout'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('produtos/', include('products.urls')),    
]
if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('cadastra/', views.register.as_view(),name='cadastra'),
    path('informacoes/', views.novo_user,name='informacoes'),
    path('login/',views.user_login, name='login'),
    path('gerenciar_usuario/',views.gerenciar_usuario, name='gerenciar_usuario'),
    path('excluir/<int:pk>/',views.excluir, name='excluir'),
    path('definir_gerente/<int:pk>/', views.definir_gerente, name='definir_gerente'),
    path('editar/<int:pk>/', views.editar, name='editar'),
    path('gerenciar_usuario/', views.gerenciar_usuario, name='gerenciar_usuario'),
   
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from . import constantes as cons


# Create your models here.

class User(models.Model):
    nome_usuario = models.OneToOneField(User, null=False, on_delete=models.PROTECT)
    nome = models.CharField(verbose_name='Nome', max_length=30)
    email = models.EmailField(verbose_name='Email',max_length=71, null=True)
    cpf = models.CharField(verbose_name='CPF', max_length=14)
    data_de_nascimento = models.DateField(verbose_name='Data de Nascimento' )
    genero = models.CharField(max_length=1, null=True, verbose_name='Sexo',
                              choices=(
                                  (cons.SEXO_MASCULINO[0], cons.SEXO_MASCULINO[1]),
                                  (cons.SEXO_FEMININO[0], cons.SEXO_FEMININO[1]),
                              )
                              )
    endereco = models.CharField(verbose_name='Endereço', max_length=50)
    observacao_endereco = models.CharField(verbose_name='Obs', max_length=50)
    cidade = models.CharField(verbose_name='Cidade', max_length=20)
    estado = models.CharField(verbose_name='Estado', max_length=20)
    cep = models.CharField(verbose_name='CEP', max_length=9)
    telefone = models.CharField(verbose_name='Telefone', max_length=13)
    celular = models.CharField(verbose_name='Celular', max_length=13)
    is_gerente = models.BooleanField(default=False)
    
    def __str__(self):
         return self.nome

users/views.py
from rest_framework.generics import get_object_or_404
from .form import FormUser
from .models import User
from . import utils
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from .form import LoginForm
from django.contrib.auth import logout
from datetime import datetime

class register(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/register.html'

#cria as informações do usuario
def novo_user(request):
    if request.method == 'POST':
        form_user = FormUser(request.POST)
        if form_user.is_valid():
            post = form_user.save(commit=False)
            post.nome_usuario = request.user
            post.save()
            return redirect('/')

    contexto = {'form':FormUser() }
    return render(request,'users/cadastra_usuaria.html',contexto)

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'],
                   password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('/')
                        
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid Login')
    else:
        form = LoginForm()
    return render(request, 'users/login.html', {'form': form})

@login_required
def sair(request):
    logout(request)
    return redirect('index')

@login_required
def gerenciar_usuario(request):

    busca = request.POST.get('buscar')
    filtro = request.POST.get('inputState')

    user = utils.obter_usuario_logado(request)
    contexto = {}
    if user.is_gerente:
        users = utils.listar_todos_usuarios(user)
        filtro = ['ID', 'Nome', 'E-Mail', 'Celular', 'Cidade', 'Estado', 'CEP', 'Administrador']
        contexto.update({'users':users,'filtro':filtro})

    return render(request, 'users/gerenciar_usuario.html',contexto)

@login_required
def excluir(request,pk):
    user = utils.obter_usuario_logado(request)
    if user.is_gerente:
        user_excuir = get_object_or_404(User,id=pk)
        user_excuir.delete()

    return redirect('gerenciar_usuario')

@login_required
def definir_gerente(request,pk):
    user = utils.obter_usuario_logado(request)
    print(pk)
    if user.is_gerente:
        gerent = get_object_or_404(User, id=pk)
        gerent = utils.definir_gerente(gerent)
        print(gerent.is_gerente)

    return redirect('gerenciar_usuario')

def editar(request,pk):
    user = utils.obter_usuario_logado(request)
    user_edit = get_object_or_404(User, pk=pk)
    if user.is_gerente:
        if request.method == 'POST':
            form = FormUser(request.POST, instance=user_edit)
            if form.is_valid:
                user_edit = form.save()
                return redirect('gerenciar_usuario')




    form = FormUser(instance=user_edit)
    data = user_edit.data_de_nascimento.strftime('%Y-%m-%d')
    return render(request,'users/cadastra_usuaria.html',{'form':form, 'data':data })
#
# def post_edit(request, pk):
#     post = get_object_or_404(Post, pk=pk)
#     if request.method == "POST":
#         form = PostForm(request.POST, instance=post)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.author = request.user
#             post.published_date = timezone.now()
#             post.save()
#             return redirect('post_detail', pk=post.pk)
#     else:
#         form = PostForm(instance=post)
#     return render(request, 'blog/post_edit.html', {'form': form})

users/templates/users/cadastra_usuaria.html
{% extends 'publico/home/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<link href="{% static 'css/cadastra_usuario.css' %}" rel="stylesheet" type="text/css">
<script  type="text/javascript" src= "{% static 'js/cadastra_usuaria.js' %}"></script>
<script  type="text/javascript" src= "{% static 'js/api_cep.js' %}"></script>

<div class="wrapper">

  <form id="formCadUsuario"  method="POST">
    {% csrf_token %}
    <div id="formHead">Insira seus Dados<hr></div>

        {{form.nome|as_crispy_field}}
        {{form.email|as_crispy_field}}
        {{form.cpf|as_crispy_field}}
        {{form.data_de_nascimento|as_crispy_field}}
        {{form.genero|as_crispy_field}}

        <div class="form-row">
          <div class="form-group col-md-4 mb-0">
            {{form.cep|as_crispy_field}}
          </div>
          
          <div class="form-group col-md-4 mb-0">
            {{form.cidade|as_crispy_field}}
          </div>

           <div class="form-group col-md-4 mb-0">
            {{form.estado|as_crispy_field}}
          </div>
        </div>
        
        {{form.endereco|as_crispy_field}}
        {{form.observacao_endereco|as_crispy_field}}

        <div class="form-row">
          <div class="form-group col-md-6 mb-0">
            {{form.telefone|as_crispy_field}}
          </div>
          
          <div class="form-group col-md-6 mb-0">
            {{form.celular|as_crispy_field}}
          </div>
        </div>          
        
         <button  type="submit" class="btn btn-success">Salvar</button>
         <button type="button" class="btn btn-danger">Cancelar</button>
  </form>
</div>

<script>
	  function open_popup(date_today) {
		document.querySelector("#id_data_de_nascimento").value = date_today;
	}

	var data = "{{data}}";
    open_popup(data);
	</script>

{% endblock %}

users/templates/users/gerenciar_usuario.html
{% extends 'publico/dashboards/dashboards_base.html' %}
{% load static %}
{% block style %}
<link href="{% static 'css/gerenciar_usuario.css' %}" rel="stylesheet" type="text/css">
{% endblock %}
{% block base %}
<h1 class="h2">Listagem de Usuários</h1>
<hr>

<div class="form-row">
    <div class="form-group col-md-6">
        <input type="search" class="form-control ds-input" placeholder="Buscar Usuário...">
    </div>

    <div class="form-group col-md-6">
        <button class="btn btn-primary">Buscar</button>
    </div>

</div>


<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">ID Usuário</th>
        <th scope="col">Nome</th>
        <th scope="col">Email</th>
        <th scope="col">Celular</th>
        <th scope="col">Cidade</th>
        <th scope="col">Estado</th>
        <th scope="col">CEP</th>
        <th scope="col">Alterar/Remover</th>
        <th scope="col">Definir Adm</th>
    </tr>
    </thead>
    <tbody>
    {% for us in users %}
    <tr>
        <th scope="row">{{us.id}}</th>
        <td>{{us.nome}}</td>
        <td>{{us.email}}</td>
        <td>{{us.celular}}</td>
        <td>{{us.cidade}}</td>
        <td>{{us.estado}}</td>
        <td>{{us.cep}}</td>
        <td>

            <a class="btn btn-primary" href="{% url 'editar' us.pk %}" role="button"> <i class="fas fa-edit"></i></a>


            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#excluirProduto{{us.pk}}">
                <i class="fas fa-trash"></i>
            </button>
        </td>
        <td>
            {% if us.is_gerente %}
            <button type="button" class="btn btn-success" data-toggle="modal" data-target="#definirADM{{us.pk}}">
                <i class="fas fa-user-check"></i>
            </button>
            {% else %}
            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#definirADM{{us.pk}}">
                <i class="fas fa-user-check"></i></i>
            </button>
            {% endif%}
        </td>
    </tr>


    <!-- Modal Excluir Produto-->
    <div class="modal fade" id="excluirProduto{{us.pk}}" tabindex="-1" role="dialog"
         aria-labelledby="excluirProdutoTitulo" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="excluirProdutoTitulo">Deseja remover o usuario?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-footer">
                    <a class="btn btn-success" href="{% url 'excluir' us.pk %}" role="button">Sim</a>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Não</button>

                </div>
            </div>
        </div>
    </div>


    <!-- Modal definir adm-->
    <div class="modal fade" id="definirADM{{us.pk}}" tabindex="-1" role="dialog" aria-labelledby="definirADMTitulo"
         aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="definirADMTitulo">Deseja alterar o status ?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-footer">
                    <a class="btn btn-primary" href="{% url 'definir_gerente' us.pk %}" role="button">Sim</a>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Não</button>

                </div>
            </div>
        </div>
    </div>


    {% endfor %}

    </tbody>

</table>

<nav aria-label="Navegação de página" style="margin-left: 25%">
    <ul class="pagination">
        <li class="page-item">
            <a class="page-link" href="#" aria-label="Anterior">
                <span aria-hidden="true">Anterior</span>
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="#" aria-label="Próximo">
                <span aria-hidden="true">Proximo</span>
            </a>
        </li>
    </ul>
</nav>
</div>


<!-- </div> -->
</div>


{% endblock %}

users/templates/users/login.html
{% extends 'publico/home/base.html' %}
{% load static %}
{% block title %}Crie sua conta{% endblock %}
{% load crispy_forms_tags %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/login.css' %}">

<div class="wrapper">
    <div id="formLogin">    

        <!-- Icone -->
        <div>
            <img src="{% static 'image/logo1.png' %}" id="logo" />
            <h1>Login</h1>
        </div>

        <!-- Login -->
        <div>
            <form method='POST'>
                {% csrf_token %}
                {{ form }}
                 <input class="btn btn-primary" type="submit" value="Login">
            </form>
        </div>
       
    </a>
        <!-- Esqueci Senha / Cadastrar-se -->
        <div id="formFooter">
            <a class="finalForm" href="#">Esqueceu a senha?</a>
            <a class="finalForm" href="{% url 'cadastra' %}">Cadastrar-se</a>
        </div>
        
    </div>
</div>

{% endblock %}

users/templates/users/register.html
{% extends 'publico/home/base.html' %}
{% load static %}
{% block title %}Crie sua conta{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<link href="{% static 'css/cadastra_usuario.css' %}" rel="stylesheet" type="text/css">
<div class="wrapper">
 <form id="formCadUsuario"  method="POST">
    <div id="formHead">Insira seus Dados<hr></div>
           {% csrf_token %}
            {{ form|crispy }}
            <input class="btn btn-primary" type="submit" value="Registrar">
    </form>
</div>
{% endblock %}