cp/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.contrib.auth import views as v
from users.views import user_login
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
	path('',views.home,name='home'),
    path('accounts/login/', user_login, name='login'),
    path('login/', user_login, name='login'),
    path('accounts/logout/', v.logout_then_login, name='logout'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('produtos/', include('products.urls')),    
]
if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path, include
from . import views

urlpatterns = [

    path('cadastrar/', views.cadastra_produtos, name='cadastrar_produtos'),
    path('gerenciar_produtos/', views.gerenciar, name='gerenciar_produtos'),
    path('excluir_produto/<pk>', views.excluir, name='excluir_produto'),
    path('editar_produto/<pk>', views.editar, name='editar_produto'),
    path('comprar_produto/<pk>', views.comprar, name='comprar_produto'),
    path('confirmar_comprar/<pk>', views.confirmar_comprar, name='confirmar_comprar'),
    path('meus_pedidos/', views.meus_pedido, name='meus_pedidos'),
    path('get_name_by_id/', views.get_name_by_id, name='get_name_by_id'),
    path('gerenciar_dashboard/', views.gerenciar_dashboard, name='gerenciar_dashboard'),
]

products/models.py
from django.db import models
from .constantes import CATEGORIAS, COR, STATUS_DA_COMPRA, FORMA_DE_PAGAMENTOS, EFETUADO
from users.models import User


# Create your models here.
class Produto(models.Model):
    nome = models.CharField('Nome Do Produto', max_length=200)
    preco = models.DecimalField('Preço em R$', max_digits=100, decimal_places=2)
    categoria = models.PositiveIntegerField('Categoria', choices=(CATEGORIAS))
    cor = models.PositiveIntegerField('Cor', choices=(COR))
    tamanho_em_cm = models.DecimalField('Tamanho em cm', null=True, max_digits=100, decimal_places=2)
    imagem = models.ImageField('Imagem do Produto', upload_to='produtos/imagens/')

    def __str__(self):
        return self.nome


class CartaoDeCreditoDebito(models.Model):
    nome_no_cartao = models.CharField('Nome No Cartao', max_length=100)
    numero_do_cartao = models.CharField('Número do Cartão', max_length=16)
    mes_data_de_expiracao = models.CharField('Mês ', max_length=2)
    ano_data_de_expiracao = models.CharField('Ano ', max_length=2)
    codigo_cvv = models.CharField('Código de segurança (CVV)', max_length=4)

    def __str__(self):
        return self.numero_do_cartao


class Boleto(models.Model):
    codigo = models.CharField('Número do Código de Barras', max_length=48)

    def __str__(self):
        return self.codigo

class Compra(models.Model):
    boleto = models.ForeignKey(Boleto, on_delete=models.CASCADE, related_name='Produto',
                               blank=True, null=True)
    cartao_de_credito_ou_debito = models.ForeignKey(CartaoDeCreditoDebito, on_delete=models.CASCADE, related_name='Produto',
                                                    blank=True, null=True)
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE, related_name='Produto')
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name='User')
    data_da_compra = models.DateTimeField('Data da Compra')
    forma_de_pagamento = models.PositiveIntegerField('Forma de Pagamento', choices=FORMA_DE_PAGAMENTOS)
    status_da_compra = models.PositiveIntegerField('Status da Compra', choices=STATUS_DA_COMPRA,
                                                   default=EFETUADO[0])

    def __str__(self):
        return self.produto.nome + '/' + self.usuario.nome

products/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, redirect, HttpResponse
from .form import ProdutForm, FormaDePagamento, Cartao
from .models import Produto, Compra, CartaoDeCreditoDebito, Boleto
from users import utils
from datetime import datetime
from . import constantes as cons
from datetime import *
from users.models import User


# Create your views here.

def cadastra_produtos(request):
    context = {}

    if request.method == 'POST':
        produt = ProdutForm(request.POST, request.FILES)
        print(produt.errors)
        if produt.is_valid():
            produt.save()
        sucess = ['Produto Cadastrado Com Sucesso']
        context.update({'sucess': sucess})

    context.update({'form': ProdutForm()})
    return render(request, 'products/cadastrar.html', context)


def gerenciar(request):
    produtos = Produto.objects.all()
    context = {'produtos': produtos}

    return render(request, 'products/gerenciar_produto.html', context)


def excluir(request, pk):
    user = utils.obter_usuario_logado(request)
    if user.is_gerente:
        prod_excuir = Produto.objects.get(id=pk)
        prod_excuir.delete()

    return redirect('gerenciar_produtos')


def editar(request, pk):
    user = utils.obter_usuario_logado(request)
    prod_edit = Produto.objects.get(id=pk)
    if user.is_gerente:
        if request.method == 'POST':
            form = ProdutForm(request.POST, instance=prod_edit)
            if form.is_valid():
                prod_edit = form.save()
                return redirect('gerenciar_produtos')

    form = ProdutForm(instance=prod_edit)

    return render(request, 'products/cadastrar.html', {'form': form})


@login_required
def comprar(request, pk):
    user = utils.obter_usuario_logado(request)
    produto = Produto.objects.get(id=pk)
    data_compra = datetime.now()

    if request.method == 'POST':

        id_foma_de_pagamento = int(request.POST.get('forma_de_pagamento'))

        # nova compra
        nova_compra = Compra()
        nova_compra.usuario = user
        nova_compra.produto = produto
        nova_compra.data_da_compra = datetime.now()
        nova_compra.forma_de_pagamento = id_foma_de_pagamento

        if id_foma_de_pagamento in cons.BOLETO:
            boleto = Boleto()
            data_vencimento = data_compra + timedelta(days=7)
            data_vencimento.strftime("%m/%d/%Y")
            data_compra.strftime("%m/%d/%Y")

            print(nova_compra.produto.preco)
            boleto.codigo = 'http://www.sicadi.com.br/mhouse/boleto/boleto3.php?' \
                            'numero_banco=341-7&' \
                            'local_pagamento=PAG%C1VEL+EM+QUALQUER+BANCO+AT%C9+O+VENCIMENTO&' \
                            'cedente=Pedras+Campinas+Ltda&' \
                            'data_documento=' + data_compra.strftime("%m/%d/%Y") + '&' \
                                                                                   'numero_documento=DF+00113&' \
                                                                                   'especie=&' \
                                                                                   'aceite=N&' \
                                                                                   'data_processamento=' + data_compra.strftime(
                "%m/%d/%Y") + '&' \
                              'uso_banco=&' \
                              'carteira=179&' \
                              'especie_moeda=Real&' \
                              'quantidade=1&' \
                              'valor=' + str(nova_compra.produto.preco) + '&' \
                                                                          'vencimento=' + data_vencimento.strftime(
                "%m/%d/%Y") + '&' \
                              'agencia=0049&' \
                              'codigo_cedente=10201-5&' \
                              'meunumero=00010435&' \
                              'valor_documento=' + str(nova_compra.produto.preco) + '&' \
                                                                                    'instrucoes=Taxa+de+visita+de+suporte%0D%0AAp%F3s+o+vencimento+R%24+0%2C80+ao+dia&' \
                                                                                    'mensagem1=&' \
                                                                                    'mensagem2=&' \
                                                                                    'mensagem3=ATEN%C7%C3O%3A+N%C3O+RECEBER+AP%D3S+15+DIAS+DO+VENCIMENTO&' \
                                                                                    'sacado=&' \
                                                                                    'Submit=Enviar'
            # salvar boleto
            boleto.save()

            # salvar compra
            nova_compra.boleto = boleto
            # nova_compra.status_da_compra=cons.EFETUADO[0]

            nova_compra.save()

            return meus_pedido(request)


        else:
            form_cartao = Cartao(request.POST, request.FILES)
            # print(form_cartao.errors)
            # print(form_cartao.is_valid())
            if form_cartao.is_valid():
                cartao_salvo = form_cartao.save()
                print(cartao_salvo.id)

                nova_compra.cartao_de_credito_ou_debito = cartao_salvo
                nova_compra.save()
                # nova_compra.status_da_compra
                return meus_pedido(request)

    context = {'produto': produto, 'nome_user': user.nome, 'data': data_compra.strftime("%m/%d/%Y"),
               'forma_de_pagamento': FormaDePagamento(),
               'cartao': Cartao()}

    return render(request, 'products/comprar.html', context)


def confirmar_comprar(request, pk):
    user = utils.obter_usuario_logado(request)
    produto = Produto.objects.get(id=pk)
    comp = Compra(produto=produto, usuario=user)
    comp.save()
    return redirect('home')


def meus_pedido(request):
    user = utils.obter_usuario_logado(request)
    compras: Compra = Compra.objects.filter(usuario=user)

    context = {'compras': compras}

    return render(request, 'products/meus_pedidos.html', context)


def get_name_by_id(request):
    data = {
        'nome': False
    }

    pk = int(request.GET.get('pk', None))
    print(pk)

    for nome in cons.STATUS_DA_COMPRA:

        if pk == nome[0]:
            data['nome'] = nome[1]

    for nome in cons.FORMA_DE_PAGAMENTOS:
        if pk == nome[0]:
            data['nome'] = nome[1]

    return JsonResponse(data)


def gerenciar_dashboard(request):
    vendas = Compra.objects.all()
    total_de_vendas = len(vendas)
    total_de_produtos = len(Produto.objects.all())
    total_de_usuarios = len(User.objects.all())

    context = {'total_de_vendas': total_de_vendas,
               'total_de_produtos': total_de_produtos,
               'total_de_usuarios': total_de_usuarios,
               'vendas':vendas}

    return render(request, 'products/gerenciar_dashboard.html',context)

products/templates/products/cadastrar.html
{% extends 'publico/dashboards/dashboards_base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block style %}
<link href="{% static 'css/cadastroProduto.css' %}" rel="stylesheet" type="text/css">
{% endblock %}
{% block base %}
<div class="container"style="margin-left:0%">
            <h1 class="h2">Cadastro de Produtos</h1>
            <form enctype='multipart/form-data' method="post">
                                    {% for s in sucess %}
                      <div class="alert alert-success alert-dismissible fade show" role="alert">
 {{s}}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
                    {% endfor %}

                {% csrf_token %}
                {{ form|crispy }}
                    <button  type="submit" class="btn btn-primary">Enviar </button>
                    <button type="reset" class="btn btn-warning">Limpar</button>
                    
              
            </form>
 </div>       
{% endblock %}

products/templates/products/comprar.html
{% extends 'publico/home/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<link href="{% static 'css/Verificarcompra.css' %}" rel="stylesheet" type="text/css">
<div class="wrapper">

    <div id="formCadUsuario">
        <div id="formHead">Verificação de Compra
            <hr>
        </div>

        <div class="col-sm-2">
            <ul type="none">
                <div>
                    <div class="product-imagem">
                        <div class="place-container">
                            <li class="li-produto"><img class="div-produto" src="{{produto.imagem.url}}"
                                                        width="500" height="300" style="margin: 0 0 0 70px"></a>

                            </li>
                        </div>
                    </div>
                </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-12">
                <label for="inputNome">Produto: {{produto.nome}}</label>
            </div>

            <div class="form-group col-md-12">
                <label for="inputEmail">Nome do Usuário: {{nome_user}}</label>
            </div>
        </div>


        <div class="form-group">
            <label for="inputEndereco">Preço da Compra: {{produto.preco}}</label>
        </div>

        <div class="form-group">
            <label for="inputObs">Data da Compra: {{data}}</label>
        </div>

 <form id="form" method="post">
        <div class="form-group">
            {{forma_de_pagamento|crispy }}
        </div>

        <div class="form-group">

                {% csrf_token %}
                <div class="collapse" id="collapseCartao">
                    {{cartao.nome_no_cartao|as_crispy_field}}

                    <div id="dataCartao" class="form-row">
                        <div class="form-group col-md-6 mb-0">
                            {{cartao.numero_do_cartao|as_crispy_field}}
                        </div>

                        <div class="form-group col-md-6 mb-0">
                            {{cartao.codigo_cvv|as_crispy_field}}
                        </div>
                    </div>

                    <label for="dataCartao">Data de Vencimento do Cartão</label>
                    <div id="dataCartao" class="form-row">
                        <div class="form-group col-md-6 mb-0">
                            {{cartao.mes_data_de_expiracao|as_crispy_field}}
                        </div>

                        <div class="form-group col-md-6 mb-0">
                            {{cartao.ano_data_de_expiracao|as_crispy_field}}
                        </div>
                    </div>


                </div>
                <button id="submitButton" type="submit" class="btn btn-success">
                    <i class="fas fa-check"></i> Finalizar</a>
                </button>

                <a class="btn btn-danger" href="{% url 'home' %}" role="button"><i class="far fa-times-circle"></i>
                    Cancelar</a>

            </form>
        </div>


    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Confirmar Compra</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <h3>Confirmar Compra</h3>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <a href="{% url 'confirmar_comprar' produto.pk %}">
                        <button type="button" class="btn btn-primary">Confirmar</button>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.min.js"></script>
    <script>


    $('#id_forma_de_pagamento').on('change', function() {



        if(this.value == 67){
           $('#collapseCartao').collapse('hide')
        }

         else if(this.value == 34){
            $('#collapseCartao').collapse('show')
        }

        else if(this.value == 89){
            $('#collapseCartao').collapse('show')
        }
        else{
            $('#collapseCartao').collapse('hide')
        }



    })

    $( "#submitButton" ).click(function() {

       if ($('#id_forma_de_pagamento').val()!='' ){
        $('form').submit()
       }

    });



    </script>
    {% endblock %}

products/templates/products/gerenciar_dashboard.html
{% extends 'publico/dashboards/dashboards_base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block style %}
<link href="{% static 'css/listaProduto.css' %}" rel="stylesheet" type="text/css">
{% endblock %}
{% block base %}




<h1 class="h2">Dashboard - Painel de Controle</h1>
<h1 class="h2">Bem Vindo Administrador</h1><br/>

<div class="form-row">
    <div class="form-group col-md-4">
        <div class="card text-center bg-info" style="width: 18rem">
            <div class="card-body">

                <h5 class="card-title">Total de Vendas Realizadas</h5>
                <p class="card-text">{{total_de_vendas}}</p>

            </div>
        </div>
    </div>

    <div class="form-group col-md-4">

        <div class="card text-white text-center bg-warning" style="width: 18rem">
            <div class="card-body">
                <h5 class="card-title">Total de Produtos Cadastrados</h5>
                <p class="card-text">{{total_de_produtos}}</p>

            </div>
        </div>

    </div>


    <div class="form-group col-md-4">

        <div class="card text-center bg-success" style="width: 18rem"></a>
            <div class="card-body">
                <h5 class="card-title">Total de Usuários Cadastrados</h5>
                <p class="card-text">{{total_de_usuarios}}</p>

            </div>
        </div>
    </div>

</div>


<div class="row">


</div>

<h1 class="h2">Histórico de Vendas</h1>
<input type="search" class="form-control ds-input" placeholder="Buscar Vendas..."/>
<table class="table table-striped" style="width:1100px">
    <thead>
    <tr>
        <th scope="col">ID Venda</th>
        <th scope="col">Nome do Produto</th>
        <th scope="col">Nome do Usuário</th>
        <th scope="col">Preço da Compra em R$</th>
        <th scope="col">Data da Compra</th>
        <th scope="col">Forma de Pagamento</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <th scope="row">1</th>
        <td>Pedra1</td>
        <td>Renato Carlos</td>
        <td>90</td>
        <td>24/08/2019</td>
        <td>Boleto Bancário</td>

    </tr>
    {% for v in vendas %}





        <tr>
        <th scope="row">{{v.id}}</th>
        <td>{{v.produto.nome}}</td>
        <td>{{v.usuario.nome}}</td>
        <td>{{v.produto.preco}}</td>
        <td>{{v.data_da_compra|date:"d/m/Y"}}</td>
        <td ><label id="{{v.id}}"></label></td>

        </tr>

    <script>

       $.ajax({
        url: '{% url "get_name_by_id" %}',
        data: {
          'pk': {{v.forma_de_pagamento}}
        },
        dataType: 'json',
        success: function (data) {
          if (!data.nome) {
            alert('Falha ao buscar detalhes da categoria');
          } else {

          $( "#{{v.id}}" ).text(data.nome)

          }
        }
      });
</script>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

products/templates/products/gerenciar_produto.html
{% extends 'publico/dashboards/dashboards_base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block style %}
<link href="{% static 'css/listaProduto.css' %}" rel="stylesheet" type="text/css">
{% endblock %}
{% block base %}

<h1 class="h2">Listagem de Produtos</h1>
<hr>

<div class="form-row">

    <div class="form-group col-nd-6">
    <a href="{% url 'cadastrar_produtos' %}">
    <button class="btn btn-primary">Cadastar Produto</button>
    </a>
    </div>

    <div class="form-group col-md-6">
    <input type="search" class="form-control ds-input" placeholder="Buscar Produtos...">
    </div>

    <div class="form-group col-nd-6">
    <button class="btn btn-primary">Buscar</button>
    </div>

    </div>


<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">ID Produto</th>
        <th scope="col">Nome</th>
        <th scope="col">Categoria</th>
        <th scope="col">Cor</th>
        <th scope="col">Tamanho em cm</th>
        <th scope="col">Preço em R$</th>
        <th scope="col">Alterar/Remover</th>
    </tr>
    </thead>
    <tbody>
    {% for p in produtos %}
    <tr>
        <th scope="row">{{p.id}}</th>
        <td>{{p.nome}}</td>
        <td>{{p.categoria}}</td>
        <td>{{p.cor}}</td>
        <td>{{p.tamanho_em_cm}}</td>
        <td>{{p.preco}}</td>
        <td>
            <a href="{% url 'editar_produto' p.pk %}">
                <button type="button" class="btn btn-primary">
                    <i class="fas fa-edit"></i>
                </button>
            </a>
            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#excluirProduto{{us.pk}}">
                <i class="fas fa-trash"></i>
            </button>
        </td>
    </tr>
    <tr>


        <!-- Modal Excluir Produto-->
        <div class="modal fade" id="excluirProduto{{us.pk}}" tabindex="-1" role="dialog"
             aria-labelledby="excluirProdutoTitulo" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="excluirProdutoTitulo">Deseja excluir o produto?</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                    <div class="modal-footer">
                        <a class="btn btn-success" href="{% url 'excluir_produto' p.pk %}" role="button">Sim</a>
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Não</button>

                    </div>
                </div>
            </div>
        </div>


        {% endfor %}
    </tbody>
</table>


<!-- Modal Excluir Produto-->
<div class="modal fade" id="excluirProduto" tabindex="-1" role="dialog" aria-labelledby="excluirProdutoTiltulo"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="excluirProdutoTiltulo">Deseja excluir o produto?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Não</button>
                <button type="button" class="btn btn-primary">Sim</button>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}

products/templates/products/meus_pedidos.html
{% extends 'publico/home/base.html' %}
{% load static %}
{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<nav class="navbar navbar-light" style="background-color: #79b2c5">
                    <img src="{% static 'image/logo1.png' %}" id="logo" />


                    <ul class="navbar-nav px-3">
                         <li class="nav-item text-nowrap">
                              <img src="{% static 'image/male.png' %}" id="user"/>
                         </li>
                         <li class="nav-item text-nowrap">
                              <a class="nav-link" href="/">Sair</a>
                         </li>
                    </ul>
          </nav>






               <link href="{% static 'css/cadastroProduto.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'products/css/main.css' %}" rel="stylesheet" type="text/css">



<h1 class="h2" style=" justify-content: center;
  text-align: center;">Meus Pedidos</h1>
<hr>
<script src="{% static 'products/js/progress-bar.js' %}"></script>


{% for comp in compras %}
<div class="container">
<div class="card mt-3">
    <div style="background=#fff" class="{{comp.id}}">  </div>
        <script>
        //pegar o nome do status da compra e gerar a barra de progresso
          $.ajax({
        url: '{% url "get_name_by_id" %}',
        data: {
          'pk': {{comp.status_da_compra}}
        },
        dataType: 'json',
        success: function (data) {
          if (!data.nome) {
            alert('Falha ao buscar detalhes da categoria');
          } else {


            //we can set animation delay as following in ms (default 1000)
            ProgressBar.singleStepAnimation = 1500;

            ProgressBar.init(

            ['Em Analise','Aprovado','Preparando Entrega','Transportadora','Pedidos Entregues',
             ],
              data.nome,
              '{{comp.id}}' // created this optional parameter for container name (otherwise default container created)
            );



          }
        }
      });

       $.ajax({
        url: '{% url "get_name_by_id" %}',
        data: {
          'pk': {{comp.forma_de_pagamento}}
        },
        dataType: 'json',
        success: function (data) {
          if (!data.nome) {
            alert('Falha ao buscar detalhes da categoria');
          } else {

            var star = $( "#{{comp.id}}" ).first().text();
            star = $( "#{{comp.id}}" ).first().text(star +data.nome)




          }
        }
      });




        </script>
        <div class="card-body">
            <br>
            <h5 class="card-title">Pedido Realizado No dia {{comp.data_da_compra}}</h5>
            <br>
            <p class="card-text" ><label>Produto:</label> {{comp.produto.nome}}</p>
            <p class="card-text" id="{{comp.id}}"><label>Forma de Pagamento:</label> </p>
            <p class="card-text" ><label>Valor: </label>{{comp.produto.preco}} </p>
            {% if comp.boleto %}
            <a href='{{comp.boleto.codigo}}' class="btn btn-primary" target="_blank">Boleto</a>
            {% endif %}
        </div>
    </div>
    </div>
    {% endfor%}





 {% endblock %}